name: CI build

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8' 

      - name: Install dotnet format
        run: dotnet tool install --global dotnet-format

      - name: Setup PATH for .NET tools
        run: echo "$HOME/.dotnet/tools" >> $GITHUB_PATH

      - name: Run dotnet format
        run: dotnet format TilbudsPlatform/TilbudsPlatform.core.csproj --verify-no-changes --verbosity diagnostic > format-output.log

      - name: Run dotnet format on solution (.sln)
        run: dotnet format TilbudsPlatform/TilbudsPlatform.sln --verify-no-changes --verbosity diagnostic > format-output-sln.log 

      - name: Fail on unformatted code
        if: failure()
        run: echo "Code formatting issues found. Please run 'dotnet format' locally and commit the changes."

      - name: Run Unit Tests
        run: dotnet test TilbudsPlatform.Tests/Tests/UnitTests/UnitTests.csproj --no-build --verbosity normal

      - name: Run Integration Tests
        run: dotnet test TilbudsPlatform.Tests/Tests/IntegrationTests/IntegrationTests.csproj --no-build --verbosity normal