name: CI build

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8'

      - name: Install dotnet format
        run: dotnet tool install --global dotnet-format

      - name: Setup PATH for .NET tools
        run: echo "$HOME/.dotnet/tools" >> $GITHUB_PATH

      - name: Run dotnet format
        run: dotnet format TilbudsPlatform/TilbudsPlatform.core.csproj --verify-no-changes --verbosity diagnostic > format-output.log

      - name: Run dotnet format on solution (.sln)
        run: dotnet format TilbudsPlatform/TilbudsPlatform.sln --verify-no-changes --verbosity diagnostic > format-output-sln.log

      - name: Fail on unformatted code
        if: failure()
        run: echo "Code formatting issues found. Please run 'dotnet format' locally and commit the changes."

      - name: Clean up obj and bin directories
        run: |
          find . -type d -name 'obj' -exec rm -rf {} +
          find . -type d -name 'bin' -exec rm -rf {} +

      - name: Run Unit Tests and Integration Tests
        run: dotnet test TilbudsPlatform.Tests/TilbudsPlatform.Tests.csproj --no-build --verbosity detailed --logger "trx;LogFileName=./test-results.trx"

      - name: Check if test-results.trx exists
        run: |
          if [ -f ./test-results.trx ]; then
            echo "Test results file found."
          else
            echo "No test results file found."
            exit 1
          fi

      - name: Upload Test Results as Artifact
        if: success() || failure()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: ./test-results.trx

      - name: Show Test Results
        if: success() || failure()
        run: |
          echo "Test results:"
          cat ./test-results.trx
