name: CI/CD Build and Docker Push

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    env:
      ASPNETCORE_ENVIRONMENT: Development

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8'

      - name: Install dotnet format
        run: dotnet tool install --global dotnet-format

      - name: Setup PATH for .NET tools
        run: echo "$HOME/.dotnet/tools" >> $GITHUB_PATH

      - name: Run dotnet format
        run: dotnet format TilbudsPlatform/TilbudsPlatform.core.csproj --verify-no-changes --verbosity diagnostic > format-output.log

      - name: Run Unit Tests and Integration Tests
        run: dotnet test TilbudsPlatform.Tests/TilbudsPlatform.Tests.csproj --logger "trx;LogFileName=test-results.trx"

      - name: Upload Test Results as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: TilbudsPlatform.Tests/TestResults/test-results.trx

  build-and-push-docker:
    runs-on: ubuntu-latest

    env:
      ASPNETCORE_ENVIRONMENT: Development

    steps:
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Login to DigitalOcean Registry
        run: |
          doctl registry login

      - name: Build Docker Image
        run: |
          docker build \
            --build-arg ASPNETCORE_ENVIRONMENT=Development \
            -t my-image:${{ github.sha }} \
            -f TilbudsPlatform/Dockerfile TilbudsPlatform

      - name: Tag Docker Image for DigitalOcean Registry
        run: |
          docker tag my-image:${{ github.sha }} registry.digitalocean.com/tilbudsplatform-registry/my-image:${{ github.sha }}

      - name: Push Docker Image to DigitalOcean Registry
        run: |
          docker push registry.digitalocean.com/tilbudsplatform-registry/my-image:${{ github.sha }}
